/* ============================================================
   EXERCISE MEDIA — passaggi di esecuzione (IT) dal dataset esercizi
   (uso educativo/non commerciale). GIF in assets/gifs/<key>.gif
   ============================================================ */
const EXERCISE_STEPS = {
  legpress: ["Regolare il sedile e la pedana della macchina da slitta in una posizione comoda.", "Sedersi sulla macchina da slitta con la schiena contro lo schienale e i piedi alla larghezza delle spalle sulla pedana.", "Afferrare le maniglie ai lati del sedile per garantire stabilità.", "Allontanare la pedana dal corpo estendendo le gambe e mantenendo i talloni sulla pedana.", "Continua a spingere finché le gambe non sono quasi completamente estese, ma senza bloccare le ginocchia.", "Fare una pausa per un momento nella parte superiore del movimento, quindi abbassare lentamente la pedana verso il corpo piegando le ginocchia.", "Ripetere per il numero di ripetizioni desiderato."],
  legext: ["Regola l'altezza del sedile e lo schienale della macchina per adattarli al tuo corpo.", "Sedersi sulla macchina con la schiena appoggiata allo schienale e i piedi sul poggiapiedi.", "Afferrare le maniglie o le barre laterali per garantire stabilità.", "Estendi le gambe in avanti raddrizzando le ginocchia, sollevando il peso.", "Fermati per un momento in alto, quindi abbassa lentamente il peso nella posizione iniziale.", "Ripetere per il numero di ripetizioni desiderato."],
  legcurl: ["Regola la macchina per adattarla al tuo corpo e seleziona il peso desiderato.", "Sdraiati a faccia in giù sulla macchina con le gambe dritte e i talloni contro la leva imbottita.", "Afferrare le maniglie o i lati della macchina per mantenerla stabile.", "Mantenendo ferma la parte superiore del corpo, espira e piega le gambe il più possibile senza sollevare i fianchi dal cuscino.", "Mantieni la posizione contratta per una breve pausa mentre contrai i muscoli posteriori della coscia.", "Inspira e abbassa lentamente la leva nella posizione iniziale.", "Ripetere per il numero di ripetizioni desiderato."],
  hipthrust: ["Inizia sdraiandoti sulla schiena a terra con le ginocchia piegate e i piedi appoggiati sul pavimento.", "Posiziona un bilanciere sui fianchi, tenendolo saldamente con entrambe le mani.", "Coinvolgi i glutei e i muscoli centrali, quindi solleva i fianchi da terra finché il tuo corpo non forma una linea retta dalle ginocchia alle spalle.", "Fermati un attimo in alto, contraendo i glutei.", "Abbassa lentamente i fianchi fino alla posizione iniziale.", "Ripetere per il numero di ripetizioni desiderato."],
  calf: ["Stai con i piedi a larghezza delle spalle e posiziona una barra sulla parte superiore della schiena.", "Alza i talloni da terra il più in alto possibile, usando solo le dita dei piedi.", "Fermati un attimo in cima, poi abbassa lentamente i talloni fino alla posizione di partenza.", "Ripeti per il numero desiderato di ripetizioni."],
  abductor: ["Regola l'altezza del sedile in modo che le ginocchia formino un angolo di 90 gradi.", "Sedersi sulla macchina con la schiena appoggiata allo schienale e i piedi sulle pedane.", "Metti le mani sulle maniglie laterali per stabilità.", "Coinvolgi i tuoi abduttori e allarga lentamente le gambe, lontano dalla linea mediana del tuo corpo.", "Fermati un attimo alla fine del movimento, poi riporta lentamente le gambe alla posizione di partenza.", "Ripetere per il numero di ripetizioni desiderato."],
  chestpress: ["Regolare l'altezza del sedile e posizionarsi sulla macchina con la schiena appoggiata al cuscino.", "Afferrare le maniglie con una presa prona e posizionare i gomiti con un angolo di 90 gradi.", "Spingi le maniglie in avanti finché le braccia non sono completamente distese, espirando durante il movimento.", "Fai una breve pausa alla fine del movimento, quindi ritorna lentamente alla posizione di partenza, inspirando mentre lo fai.", "Ripetere per il numero di ripetizioni desiderato."],
  chestfly: ["Regolare l'altezza del sedile e posizionarsi sulla macchina con la schiena appoggiata al cuscino.", "Afferrare le maniglie con presa prona e tenere i gomiti leggermente piegati.", "Espira e spingi le maniglie in avanti, unendole davanti al petto.", "Fai una pausa per un momento, contraendo i muscoli del torace.", "Inspira e ritorna lentamente alla posizione di partenza, permettendo ai muscoli del torace di allungarsi.", "Ripetere per il numero di ripetizioni desiderato."],
  shoulderpress: ["Regolare l'altezza del sedile e posizionarsi sulla macchina con la schiena appoggiata allo schienale.", "Afferrare le maniglie con una presa prona e posizionare le mani all'altezza delle spalle.", "Spingere le maniglie verso l'alto finché le braccia non sono completamente distese, ma non bloccare i gomiti.", "Fermati per un momento in alto, quindi abbassa lentamente le maniglie fino alla posizione iniziale.", "Ripetere per il numero di ripetizioni desiderato."],
  lateral: ["Stai in piedi con i piedi alla larghezza delle spalle e tieni un manubrio in ogni mano, palmi rivolti verso il corpo.", "Tieni la schiena dritta e attiva il core.", "Alza le braccia ai lati finché non sono parallele al pavimento, mantenendo una leggera piega dei gomiti.", "Fermati un attimo in cima, poi abbassa lentamente le braccia fino alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  tricipiti: ["Attacca una barra dritta a una macchina a cavo a carrucole alta.", "Stai rivolto verso la macchina con i piedi a larghezza delle spalle e con una leggera piega delle ginocchia.", "Afferra la barra con una presa sopra la mano, mani a larghezza delle spalle.", "Tieni i gomiti vicini ai fianchi e le braccia superiori ferme.", "Espira e spingi la barra verso il basso finché i gomiti non sono completamente estesi.", "Fermati un attimo, poi inspira e riporta lentamente la barra alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  frenchpress: ["Sdraiati disteso su una panchina con un manubrio in ogni mano, i palmi uno verso l'altro.", "Allunga le braccia dritte sul petto, tenendo i gomiti vicini al corpo.", "Abbassa i manubri verso la fronte, piegando i gomiti.", "Fermati un attimo, poi rialza le braccia fino alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  latmachine: ["Siediti di fronte alla lat machine con i piedi appoggiati a terra e le ginocchia sotto i rulli.", "Afferra la barra con una presa prona, leggermente più larga della larghezza delle spalle.", "Inclinati leggermente all'indietro e tieni il petto alto, mantenendo un leggero arco lombare.", "Tira la barra verso il petto, guidando con i gomiti e stringendo le scapole.", "Fermati un attimo in basso, poi riporta lentamente la barra alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  pulley: ["Siediti sulla macchina per il rematore con i piedi appoggiati sulle pedane e le ginocchia leggermente piegate.", "Afferra le maniglie con una presa sopra la mano, tenendo la schiena dritta e le spalle rilassate.", "Tira le maniglie verso il corpo, stringendo le scapole insieme.", "Fermati un attimo al picco del movimento, poi rilasci lentamente le maniglie alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  reversefly: ["Regola l'altezza del sedile e posizionati sulla macchina con il petto contro l'imbottitura e i piedi appoggiati sul pavimento.", "Afferrare le maniglie con una presa prona e tenere le braccia leggermente piegate.", "Espira e stringi insieme le scapole mentre tiri le maniglie indietro e verso l'esterno, lontano dal corpo.", "Fermati per un momento al picco della contrazione, quindi inspira e ritorna lentamente alla posizione di partenza.", "Ripetere per il numero di ripetizioni desiderato."],
  curl: ["Impugna il bilanciere EZ nella parte curva interna, presa supinata (palmi verso l'alto).", "Stai dritto, braccia distese, gomiti fermi ai fianchi per tutta la serie.", "Espira e solleva il bilanciere controllando il movimento, fino all'altezza del petto.", "Mantieni la contrazione per una breve pausa stringendo i bicipiti.", "Scendi lento fino a braccia distese — non rimbalzare in basso.", "La presa EZ riduce lo stress sul polso rispetto al bilanciere dritto."],
  hammer: ["Siediti su una panchina con un manubrio in ogni mano, i palmi rivolti verso il busto e le braccia distese verso il basso.", "Tieni la schiena dritta e i gomiti vicini al busto.", "Espira e arrotola il manubrio della mano destra verso la spalla, mantenendo fermo il braccio superiore.", "Continua ad alzare il manubrio finché i bicipiti non sono completamente contratti e il manubrio non è all'altezza delle spalle.", "Fermati un attimo, poi inspira e abbassa lentamente il manubrio fino alla posizione iniziale.", "Ripeti il movimento con il braccio sinistro.", "Continuare ad alternare le braccia per il numero desiderato di ripetizioni."],
  facepull: ["Fissa una maniglia di staffa a una puleggia a cavo bassa e mettiti rivolto verso la macchina.", "Afferra il manico con la mano sinistra e fai un passo indietro con il piede destro, posizionando il corpo con un leggero angolo.", "Flette leggermente le ginocchia e incurva in avanti sui fianchi, mantenendo la schiena dritta e il core attivo.", "Con il braccio sinistro teso e il palmo rivolto verso il basso, tira il manico verso il petto ritirando la scapola.", "Fermati un attimo all'inizio del movimento, stringendo la scapola.", "Rilascia lentamente la maniglia alla posizione iniziale e ripeti per il numero desiderato di ripetizioni.", "Cambia lato e ripeti l'esercizio con il braccio destro."],
  plank: ["Inizia in una posizione di plancia alta con le mani direttamente sotto le spalle e il corpo in linea retta dalla testa ai piedi.", "Coinvolgi il core e i glutei per mantenere una posizione stabile.", "Ruota il busto verso destra, sollevando il braccio destro ed estendendolo verso il soffitto.", "Mantieni i fianchi e le gambe stabili mentre giri.", "Mantieni la posizione per un momento, quindi torna alla posizione di partenza.", "Ripeti la torsione sul lato sinistro.", "Continua ad alternare i lati per il numero di ripetizioni desiderato."],
  crunch: ["Attacca una maniglia di corda a una carrucola alta e inginocchiati rivolto di spalle alla macchina.", "Tieni il manico della corda con entrambe le mani e posizionalo dietro la testa, tenendo i gomiti ai lati.", "Tieni i fianchi fermi, fletti la vita e schiaccia il busto verso le cosce.", "Fermati un attimo in fondo, poi torna lentamente alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  /* --- esercizi custom delle schede PT (lookup per nome-slug) --- */
  alzate_laterali_manubri: ["Stai in piedi con i piedi alla larghezza delle spalle e tieni un manubrio in ogni mano, palmi rivolti verso il corpo.", "Tieni la schiena dritta e attiva il core.", "Alza le braccia ai lati finché non sono parallele al pavimento, mantenendo una leggera piega dei gomiti.", "Fermati un attimo in cima, poi abbassa lentamente le braccia fino alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  panca_inclinata_manubri: ["Installa una panca inclinata con un angolo di 45 gradi.", "Siediti sulla panca con i piedi piatti a terra e la schiena premuta saldamente contro la panca.", "Tieni un manubrio in ogni mano, palmi rivolti in avanti, e sollevali all'altezza delle spalle.", "Abbassa lentamente i manubri ai lati del petto, mantenendo i gomiti a 90 gradi.", "Spingi i manubri di nuovo alla posizione iniziale, estendendo completamente le braccia.", "Ripeti per il numero desiderato di ripetizioni."],
  lat_pulldown_inversa: ["Regola la macchina a cavo in modo che la barra di trazione sia a un'altezza sopra la tua testa.", "Siediti sul sedile e afferra la barra di trazione con una presa sottomano, le mani leggermente più larghe della larghezza delle spalle.", "Tieni la schiena dritta e inclinati leggermente all'indietro.", "Tira la barra verso il petto, stringendo le scapole insieme.", "Fermati un attimo in fondo al movimento, poi rilasci lentamente la barra fino alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  lento_avanti_manubri: ["Siediti su una panchina con un manubrio in ogni mano, appoggiato sulle cosce.", "Alza i manubri all'altezza delle spalle, palmi rivolti in avanti.", "Premi i manubri verso l'alto finché le braccia non sono completamente estese sopra la testa.", "Fermati un attimo in cima, poi abbassa lentamente i manubri all'altezza delle spalle.", "Ripeti per il numero desiderato di ripetizioni."],
  pulldown_cavi_corda: ["Attacca una corda alla macchina per cavi con la massima regolazione.", "Stai rivolto verso la macchina con i piedi alla larghezza delle spalle.", "Afferra la corda con entrambe le mani, palmi rivolti verso il basso.", "Allunga completamente le braccia davanti a te, tenendo i gomiti leggermente piegati.", "Attiva i dorsali e tira lentamente la corda verso le cosce, mantenendo le braccia dritte.", "Fermati un attimo in fondo, poi rilassa lentamente la tensione e torna alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
  plank_battito_spalle: ["Inizia in una posizione di plancia alta con le mani direttamente sotto le spalle e il corpo in linea retta.", "Coinvolgi il tuo core e solleva la mano destra da terra, allungandoti per toccare la spalla sinistra.", "Riporta la mano destra a terra e ripeti con la mano sinistra toccando la spalla destra.", "Continua ad alternare i colpi sulle spalle mantenendo i fianchi e il busto stabili.", "Ripetere per il numero di ripetizioni desiderato."],
  crunch_sollevamento_gambe: ["Sdraiati sulla schiena con le braccia distese lungo i fianchi.", "Piega le ginocchia e solleva i piedi da terra, portando le cosce perpendicolari al pavimento.", "Contrai gli addominali e solleva i fianchi dal pavimento, portando le ginocchia verso il petto.", "Fai una pausa per un momento in alto, quindi abbassa lentamente i fianchi fino alla posizione iniziale.", "Ripetere per il numero di ripetizioni desiderato."],
  mountain_climber: ["Inizia in una posizione di plancia alta con le mani direttamente sotto le spalle e il corpo in linea retta.", "Coinvolgi il core e porta il ginocchio destro verso il petto, quindi cambia rapidamente e porta il ginocchio sinistro verso il petto.", "Continua ad alternare le gambe con un movimento di corsa, mantenendo i fianchi bassi e il core impegnato.", "Mantieni un ritmo costante e respira in modo uniforme durante l'esercizio.", "Ripetere per il numero di ripetizioni desiderato."],
  circuito_metabolico: ["Inizia in posizione eretta, con i piedi alla larghezza delle spalle.", "Abbassa il corpo in posizione accovacciata piegando le ginocchia e appoggiando le mani sul pavimento davanti a te.", "Rimetti i piedi in posizione di piegamenti.", "Fai una flessione, mantenendo il corpo in linea retta.", "Rimetti i piedi in posizione squat.", "Salta su esplosivamente, allungando le braccia sopra la testa.", "Atterra dolcemente e poi si abbassa subito in posizione accovacciato per iniziare la prossima ripetizione."],
  affondi_statici_con_manubri: ["Stai in piedi con un manubrio per mano lungo i fianchi, piedi alla larghezza delle spalle.", "Fai un passo avanti e posiziona il piede circa mezzo metro davanti all'altro: questa è la tua posizione fissa per tutta la serie.", "Abbassa il corpo piegando entrambe le ginocchia, tenendo la schiena dritta e il busto alto.", "Scendi finché la coscia anteriore è parallela al suolo e il ginocchio posteriore sfiora terra.", "Spingi col tallone anteriore per risalire, restando sul posto.", "Completa le ripetizioni, poi cambia gamba."],
  affondi_laterali_con_manubri: ["Stai in piedi con i piedi alla larghezza delle spalle, un manubrio per mano lungo i fianchi (o entrambe le mani su un manubrio al petto).", "Fai un passo ampio di lato, mantenendo entrambi i piedi ben piantati e le punte in avanti.", "Spingi il bacino indietro piegando la gamba del lato in cui ti sposti, mentre l'altra resta distesa.", "Scendi finché la coscia che lavora è quasi parallela al pavimento, tenendo il busto alto e la schiena neutra.", "Spingi col tallone per tornare al centro.", "Ripeti per il numero di ripetizioni desiderato, poi cambia lato."],
  crunch_panca_inclinata: ["Sdraiati su una panca di discesa con i piedi ben assicurati e le ginocchia piegate a 90 gradi.", "Metti le mani dietro la testa o sul petto.", "Attiva gli addominali e solleva la parte superiore del corpo verso le ginocchia, curvando il busto.", "Fermati un attimo in cima, poi abbassa lentamente la parte superiore del corpo fino alla posizione iniziale.", "Ripeti per il numero desiderato di ripetizioni."],
};
